# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 5gG@88
      POSTGRES_USER: autoshow_user
    ports:
    - 5432:5432
    volumes:
      - autoshow:/.db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  autoshow: